# This is a basic workflow to help you get started with Actions

name: Render-Image-Make-easy-ppm

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Preparation
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install python3 python3-pip
        python3 -m pip install --upgrade pip
        python3 -m pip install pillow scipy numpy 
    
    # Runs a single command using the runners shell
    - name: Build the program
      run: mkdir _build_ && cd _build_ && cmake .. && make && cd .. && mkdir _output_
      
    - name: Rendering - Generating PPM File
      run: ./_build_/make-easy-ppm _output_/generated.ppm
    
    - name: Rendering - Generating PNG File
      run: cd _output_ && python3 ../utils/ppm-viewer/view-ppm.py _output_/generated.ppm
    
    - name: Download the rendered picture
      uses: actions/download-artifact@v2
      with:
        name: Rendered
        path: _output_/demo.png


